const HAS = {
    defect: false,
    discontent: false,
    resentment: false,
    obsession: false,
    experience: false,
    strength: false,
    hope: false,

    acceptance: false,
    anger: false,
    armor: false,
    boundary: false,
    compassion: false,
    courage: false,
    fear: false,
    fun: false,
    gratitude: false,
    irritability: false,
    impatience: false,
    joy: false,
    pride: false,
    salvaltion: false,
    selfPity: false,
    suffering: false,
    toxicity: false,
    trauma: false,
    vulnerability: false,

    congregant: false,
    genie: false,
    guardian: false,
    martyr: false,
    paladin: false,
    seeker: false,
    smith: false,
    summoner: false,
    victim: false,
    volunteer: false,

    act: false,
    affliction: false,
    body: false,
    construct: false,
    oath: false,
    shield: false,
    stigmata: false,
    virtue: false,
    wish: false,

    brain: false,
    campaign: false,
    confusion: false,
    cross: false,
    crown: false,
    crusade: false,
    delirium: false,
    denial: false,
    dream: false,
    face: false,
    gash: false,
    gate: false,
    gut: false,
    heart: false,
    infection: false,
    love: false,
    mind: false,
    mouth: false,
    nail: false,
    nightmare: false,
    pledge: false,
    sacrifice: false,
    sarcasm: false,
    scar: false,
    service: false,
    silence: false,
    skin: false,
    soul: false,
    sternum: false,
    support: false,
    tower: false,
    tremor: false,
    wall: false,
};

module.exports = HAS;