version: '3.3'
services:
  db:
    container_name: higher-power-db-dev
    ports:
      - 32668:5432

  prisma:
    container_name: higher-power-prisma-dev
    depends_on:
      - db
    ports:
      - "32669:4466"
